### ISSUE TITLE
[Feature] Mouse and/or keyboard support

### ISSUE THREAD

**Issue by SaphuA** [CodeConnect/TouchVS#6]
So I am thinking this extension could be the ultimate quick-command tool (besides CTRL+Q). You'd appeal to a much bigger audience if you'd add support for keyboard and mouse controls as well.

I've already implemented mouse support using the middle mouse button to open the menu. I can't test this yet due to #5. If you like the idea, and once tested, I'll add a pull request and start working on keyboard support. I'm thinking of using a configurable hotkey (and/or menu button) to open, and arrow keys/enter/escape to navigate.

Although it'd make sense to change the name if you do... :laughing:

**Comment by AmadeusW** [comment]
That'd be really cool. I'm working on #5 
ha, yeah, we'd have to find a new name!

**Comment by AmadeusW** [comment]
This feature is released in [version 1.0.1](https://visualstudiogallery.msdn.microsoft.com/fb0207b6-ccd1-43b4-92ea-1dd0f3c58fe5). Thanks @SaphuA! :+1:
